FROM python:3.11-slim

WORKDIR /usr/src/app

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir .

CMD ["python3", "discord_bot/discord_connection.py"]



