version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dc
    restart: always
    tty: true
    stdin_open: true
    env_file: project_ctx/.env
    environment:
      - SHELLARC_PROJECT_CTX
    volumes:
      - ${SHELLARC_PROJECT_CTX}:${SHELLARC_PROJECT_CTX}
      - /home/miduki/null_project_2026/version_management:/home/miduki/null_project_2026/version_management

  itemi_action:
    build:
      context: .
      dockerfile: Dockerfile.itemi
    restart: always
    tty: true
    stdin_open: true
    env_file: project_ctx/.env
    environment:
      - SHELLARC_PROJECT_CTX
    volumes:
      - ${SHELLARC_PROJECT_CTX}:${SHELLARC_PROJECT_CTX}
      - /home/miduki/null_project_2026/version_management:/home/miduki/null_project_2026/version_management
      - /home/.config:/home/.config

  ai_chat:
    build:
      context: .
      dockerfile: Dockerfile.nullai
    restart: always
    tty: true
    stdin_open: true
    env_file: project_ctx/.env
    environment:
      - SHELLARC_PROJECT_CTX
    volumes:
      - ${SHELLARC_PROJECT_CTX}:${SHELLARC_PROJECT_CTX}
      - /home/miduki/null_project_2026/version_management:/home/miduki/null_project_2026/version_management