version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dc
    restart: always
    tty: true
    stdin_open: true
    env_file: project_ctx/.env
    environment:
      - SHELLARC_PROJECT_CTX

  itemi_action:
    build:
      context: .
      dockerfile: Dockerfile.itemi
    restart: always
    tty: true
    stdin_open: true
    env_file: project_ctx/.env
    environment:
      - SHELLARC_PROJECT_CTX

  ai_chat:
    build:
      context: .
      dockerfile: Dockerfile.nullai
    restart: always
    tty: true
    stdin_open: true
    env_file: project_ctx/.env
    environment:
      - SHELLARC_PROJECT_CTX
